import assert from 'node:assert/strict';
import test from 'node:test';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import { BSON, MongoClient, ObjectId } from 'mongodb';
import {
  collectionInventory,
  DELETE_COLLECTIONS,
  deleteMongoData,
  mongoPlan,
  PRESERVE_COLLECTIONS,
  readMongoState,
} from '../mongo.mjs';
import { checkSnapshot, makePlan } from '../safety.mjs';

test('isolated Mongo replica: rollback, all lead-related collections, preserved config and second database', async () => {
  // URI is generated by a NEW loopback-only ephemeral replica set. Never reads
  // application/cleanup credentials, never connects to Railway or a real CRM.
  const server = await MongoMemoryReplSet.create({ replSet: { count: 1, ip: '127.0.0.1' } });
  const client = new MongoClient(server.getUri());
  try {
    await client.connect();
    const db = client.db('isolated_cleanup_fixture');
    const untouched = client.db('untouched_fixture');
    await untouched.collection('leads').insertOne({ marker: 'must survive' });
    const target = {
      crm: { database: db.databaseName, crmProjectId: 'crm-fixture' },
      omnicus: { projectId: 'omni-fixture' },
    };
    for (const name of DELETE_COLLECTIONS) {
      await db.collection(name).insertMany([
        {
          _id: new ObjectId(),
          email: 'first@fixture.test',
          attachment: { storageKey: `leads/test/${name}.pdf` },
        },
        { _id: new ObjectId(), email: 'second@fixture.test', leadId: new ObjectId() }, // deliberate orphan
      ]);
      await db.collection(name).createIndex({ email: 1 });
    }
    for (const name of PRESERVE_COLLECTIONS)
      await db
        .collection(name)
        .insertOne(
          name === 'omnicusconnections'
            ? { crmProjectId: 'crm-fixture', omnicusProjectId: 'omni-fixture', status: 'DISABLED' }
            : { marker: `preserve-${name}` },
        );
    const configBefore = {};
    for (const name of PRESERVE_COLLECTIONS)
      configBefore[name] = await db.collection(name).find({}).toArray();
    const inventory = await collectionInventory(db);
    const session = client.startSession();
    try {
      session.startTransaction({
        readConcern: { level: 'snapshot' },
        writeConcern: { w: 'majority' },
      });
      const state = await readMongoState(db, session, target, inventory, BSON.EJSON);
      const plan = makePlan('crm', target, mongoPlan(state, BSON.EJSON));
      assert.equal(plan.snapshot.deleteCounts.leads, 2);
      assert.equal(plan.snapshot.retainedFiles.length, DELETE_COLLECTIONS.length);
      await deleteMongoData(db, session, state);
      await session.abortTransaction();
      assert.equal(await db.collection('leads').countDocuments(), 2);

      await db.collection('leads').updateOne({}, { $set: { email: 'changed@fixture.test' } });
      session.startTransaction();
      const changed = await readMongoState(db, session, target, inventory, BSON.EJSON);
      assert.throws(() => checkSnapshot(plan, mongoPlan(changed, BSON.EJSON)), /changed/);
      await deleteMongoData(db, session, changed);
      await session.commitTransaction();
      for (const name of DELETE_COLLECTIONS) {
        assert.equal(await db.collection(name).countDocuments(), 0, name);
        assert.equal((await db.collection(name).indexes()).length, 2, `${name} indexes preserved`);
      }
      for (const name of PRESERVE_COLLECTIONS)
        assert.deepEqual(await db.collection(name).find({}).toArray(), configBefore[name]);
      assert.equal(await untouched.collection('leads').countDocuments(), 1);
    } finally {
      await session.endSession();
    }
    await db.collection('unreviewed_collection').insertOne({ leadId: new ObjectId() });
    await assert.rejects(collectionInventory(db), /Unreviewed/);
  } finally {
    await client.close();
    await server.stop();
  }
});
