export const globalPermissions = [
  'projects:create',
  'projects:read',
  'users:manage',
  'users:read',
  'roles:manage',
] as const;

export const projectPermissions = [
  'project:read',
  'email:read',
  'email:send',
  'email:manage',
  'project:manage',
  'members:manage',
  'contacts:read',
  'contacts:manage',
  'contacts:update',
  'contacts:export',
  'contacts:merge',
  'tags:read',
  'tags:manage',
  'automation:read',
  'automation:manage',
  'integrations:manage',
  'channels:read',
  'channels:manage',
  'channels:rotate_secrets',
  'broadcasts:read',
  'broadcasts:create',
  'broadcasts:launch',
  'broadcasts:pause',
  'broadcasts:cancel',
  'media:read',
  'media:manage',
  'templates:read',
  'templates:manage',
] as const;

export const allPermissionCodes = [...globalPermissions, ...projectPermissions] as const;

export const SUPER_ADMIN_ROLE = 'super-admin';

export const systemProjectRoles = [
  {
    name: 'Project Admin',
    normalizedName: 'project-admin',
    permissions: [
      'project:read',
      'email:read',
      'email:send',
      'email:manage',
      'project:manage',
      'members:manage',
      'contacts:read',
      'contacts:manage',
      'contacts:update',
      'contacts:export',
      'contacts:merge',
      'tags:read',
      'tags:manage',
      'automation:read',
      'automation:manage',
      'integrations:manage',
      'channels:read',
      'channels:manage',
      'channels:rotate_secrets',
      'broadcasts:read',
      'broadcasts:create',
      'broadcasts:launch',
      'broadcasts:pause',
      'broadcasts:cancel',
      'media:read',
      'media:manage',
      'templates:read',
      'templates:manage',
    ],
  },
  {
    name: 'Automation Editor',
    normalizedName: 'automation-editor',
    permissions: [
      'project:read',
      'automation:read',
      'automation:manage',
      'media:read',
      'media:manage',
      'templates:read',
      'templates:manage',
    ],
  },
  {
    name: 'Integration Manager',
    normalizedName: 'integration-manager',
    permissions: [
      'project:read',
      'integrations:manage',
      'channels:read',
      'channels:manage',
      'channels:rotate_secrets',
    ],
  },
  {
    name: 'Contact Manager',
    normalizedName: 'contact-manager',
    permissions: [
      'project:read',
      'contacts:read',
      'contacts:manage',
      'contacts:update',
      'contacts:export',
      'contacts:merge',
      'tags:read',
      'tags:manage',
    ],
  },
  {
    name: 'Viewer',
    normalizedName: 'viewer',
    permissions: [
      'project:read',
      'contacts:read',
      'tags:read',
      'automation:read',
      'media:read',
      'templates:read',
    ],
  },
] as const;
