export const seedGlobalPermissions = [
  'projects:create',
  'projects:read',
  'users:manage',
  'users:read',
  'roles:manage',
] as const;

export const seedProjectPermissions = [
  'project:read',
  'email:read',
  'email:send',
  'email:manage',
  'project:manage',
  'members:manage',
  'contacts:read',
  'contacts:manage',
  'contacts:update',
  'contacts:export',
  'contacts:merge',
  'tags:read',
  'tags:manage',
  'automation:read',
  'automation:manage',
  'integrations:manage',
  'channels:read',
  'channels:manage',
  'channels:rotate_secrets',
  'broadcasts:read',
  'broadcasts:create',
  'broadcasts:launch',
  'broadcasts:pause',
  'broadcasts:cancel',
  'media:read',
  'media:manage',
  'templates:read',
  'templates:manage',
] as const;
